### ISSUE TITLE
No module named 'gunicorn'

### ISSUE THREAD

**Issue by yaelsolan** [yaelsolan/BottleWebApp#5]
when I run my app in my computer: python app.py
I get the output:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bottle.py", line 3168, in run
    server.run(app)
  File "/usr/local/lib/python3.8/dist-packages/bottle.py", line 2973, in run
    from gunicorn.app.base import Application
ModuleNotFoundError: No module named 'gunicorn'
Bottle v0.12.23 server starting up (using GunicornServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bottle.py", line 3168, in run
    server.run(app)
  File "/usr/local/lib/python3.8/dist-packages/bottle.py", line 2973, in run
    from gunicorn.app.base import Application
ModuleNotFoundError: No module named 'gunicorn'

**Comment by yaelsolan** [comment]
Yes, that's what I did after we talked.  I forgot to close the issue‫ב-11 בדצמ׳ 2022, בשעה 14:27, ‏‏Oz N Tiram ***@***.***> כתב/ה:‬﻿
Check the readme.
